plugins: fetchart embedart scrub lastgenre missing convert
directory: /music/
library: /config/musiclibrary.blb
art_filename: cover
threaded: yes
original_date: no
per_disc_numbering: no

ui:
    color: yes

paths:
    default: Albums/$albumartist/$album%aunique{}/$track - $artist - $title
    singleton: Individual\ Tracks/$artist - $title
    albumtype:soundtrack: Soundtracks/$album%aunique{}/$track - $artist - $title
    comp: Compilations/$album%aunique{}/$track - $artist - $title

asciify_paths: yes

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: yes
    log: /config/beet.log
    language: en
    detail: yes

lastgenre:
    auto: yes
    canonical: no
    source: album
    count: 3

embedart:
    auto: yes

fetchart:
    auto: yes

scrub:
    auto: no

missing:
    format: $albumartist - $album - $track - $title

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

convert:
  dest: /convert
  quiet: yes
  never_convert_lossy_files: yes

